// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('artistBio', []).controller('artistListController', function($scope, $sce) {
    var artistList;
    artistList = this;
    artistList.artists = [];
    return artistList.addArtist = function() {
      var artistNameString, artistText, url;
      artistText = artistList.artistText;
      artistNameString = artistText.split(' ').join('_');
      url = 'http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=' + artistText + '&autocorrect=1&api_key=a522b32b563f5f3789bd76e86dd69930&format=json';
      artistList.artists.push({
        text: artistText
      });
      this.requestArtist = $.ajax({
        url: url,
        datatype: 'jsonp',
        cache: true,
        success: function(data) {
          console.log(data);
          $scope.artistBio = $sce.trustAsHtml(data.artist.bio.summary);
          return artistList.artists.push({
            name: data.artist.name,
            pic: data.artist.image[2]['#text'],
            bio: data.artist.bio.summary
          });
        },
        error: function(data) {
          return console.log('Last.FM API Error: ', data);
        }
      });
      artistList.artistText = '';
      return console.log(artistList);
    };
  });

  jQuery(document).ready(function($) {});

}).call(this);


//# sourceMappingURL=artist-bio.js.map
