// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('artistBio', []);

  app.filter('reverse', function() {
    return function(items) {
      return items.slice().reverse();
    };
  });

  app.controller('artistListController', function($scope, $sce) {
    var artistList;
    $scope.trustAsHtml = $sce.trustAsHtml;
    artistList = this;
    artistList.artists = [];
    return artistList.addArtist = function() {
      var artistText, lastFMjson, url;
      artistText = artistList.artistText;
      url = 'http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=' + artistText + '&autocorrect=1&api_key=a522b32b563f5f3789bd76e86dd69930&format=json';
      lastFMjson = $.ajax({
        url: url,
        datatype: 'jsonp',
        cache: true,
        async: false,
        success: function(data) {
          return console.log(data);
        },
        error: function(data) {
          return console.log('Last.FM API Error: ', data);
        }
      }).responseJSON;
      artistList.artists.push({
        id: artistList.artists.length + 1,
        text: artistText,
        name: lastFMjson.artist.name,
        pic: lastFMjson.artist.image[2]['#text'],
        bio: lastFMjson.artist.bio.summary
      });
      return artistList.artistText = '';
    };
  });

}).call(this);


//# sourceMappingURL=artist-bio.js.map
